<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="9" time="0.360" timestamp="2021-03-28T19:33:35.028204" hostname="moriarty"><testcase classname="test_First" name="test_1" time="0.001" /><testcase classname="test_First" name="test_2" time="0.001" /><testcase classname="test_First" name="test_3" time="0.001"><failure message="AssertionError: Title doesn't match&#10;assert 'jenkins' in 'Jenkins is CI server'">def test_3():
        name="jenkins"
        title="Jenkins is CI server"
&gt;       assert name in title, "Title doesn't match"
E       AssertionError: Title doesn't match
E       assert 'jenkins' in 'Jenkins is CI server'

test_First.py:16: AssertionError</failure></testcase><testcase classname="test_Second" name="test_login" time="0.001" /><testcase classname="test_Second" name="test_checkout" time="0.001" /><testcase classname="test_Second" name="test_logout" time="0.001" /><testcase classname="test_four" name="test_responsecode" time="0.001" /><testcase classname="test_four" name="test_responsecode400" time="0.001" /><testcase classname="test_three.MyTestCase" name="test_something" time="0.001"><failure message="AssertionError: True != False">self = &lt;PyTestFramework.pytestDemos.test_three.MyTestCase testMethod=test_something&gt;

    def test_something(self):
&gt;       self.assertEqual(True, False)
E       AssertionError: True != False

test_three.py:6: AssertionError</failure></testcase></testsuite></testsuites>